"""Retrofit `data-oid` stable identifiers into existing HTML.

The `data-oid` attribute is living-slides' canonical stable selector
(see differ.py). `slive adopt` lets users bring decks generated by other
tools — frontend-slides, hand-written HTML, AI output without oids — into
the iteration loop without regenerating from scratch.

Strategies:
  role        infer a semantic role from tag/class (default)
  sequential  s{slide}-o{counter}, simplest possible
  hash        content hash, stable across regenerations of the same content
"""

from __future__ import annotations

import hashlib
import re
from html.parser import HTMLParser


# Tags that are meaningful enough to track edits on. `head`, `meta`, `link`,
# `script`, `style`, `body`, `html`, `div` (bare) are deliberately excluded.
_MEANINGFUL_TAGS = {
    "section", "article", "header", "footer", "nav", "main", "aside",
    "h1", "h2", "h3", "h4", "h5", "h6",
    "p", "blockquote", "pre", "figure", "figcaption",
    "ul", "ol", "li", "dl", "dt", "dd",
    "table", "tr", "th", "td", "caption",
    "img", "video", "audio", "picture", "svg", "canvas",
    "a", "button",
}

_SLIDE_TAGS = {"section", "article"}
_SLIDE_CLASS_HINTS = {"slide", "page", "deck-slide"}

# Map tag → semantic role (used by the role strategy).
_TAG_ROLE = {
    "h1": "title", "h2": "title", "h3": "title",
    "h4": "subtitle", "h5": "subtitle", "h6": "subtitle",
    "p": "text",
    "img": "image", "picture": "image", "svg": "image", "canvas": "image",
    "video": "video", "audio": "audio",
    "ul": "list", "ol": "list", "li": "item",
    "table": "table", "tr": "row", "td": "cell", "th": "cell",
    "a": "link", "button": "button",
    "blockquote": "quote", "pre": "code",
    "figure": "figure", "figcaption": "caption",
    "header": "header", "footer": "footer", "nav": "nav", "aside": "aside",
}

_STRATEGIES = {"role", "sequential", "hash"}


class _CollectParser(HTMLParser):
    """First pass: collect a record for every meaningful element."""

    def __init__(self, source: str):
        super().__init__(convert_charrefs=False)
        self.source = source
        self.records: list[dict] = []
        self.preserved_oids: set[str] = set()
        self._stack: list[dict] = []
        self._in_head_depth = 0

    def handle_starttag(self, tag, attrs):
        if tag == "head":
            self._in_head_depth = 1
            return
        if self._in_head_depth > 0:
            self._in_head_depth += 1
            return

        attrs_dict = dict(attrs)
        is_slide = _is_slide(tag, attrs_dict)
        existing_oid = attrs_dict.get("data-oid")
        if existing_oid:
            self.preserved_oids.add(existing_oid)

        record = None
        if tag in _MEANINGFUL_TAGS and not existing_oid:
            line, col = self.getpos()
            pos = _line_col_to_offset(self.source, line, col)
            tag_text = _extract_tag_text(self.source, pos)
            if tag_text is not None:
                record = {
                    "pos": pos,
                    "tag_text": tag_text,
                    "tag": tag,
                    "attrs": attrs_dict,
                    "is_slide": is_slide,
                    "text": "",
                }
                self.records.append(record)

        # Push a frame for tracking text accumulation regardless of whether we
        # are tagging this element — children's text still belongs to it.
        self._stack.append({"tag": tag, "record": record, "is_slide": is_slide})

    def handle_startendtag(self, tag, attrs):
        # Self-closing element: same as start, with no children.
        self.handle_starttag(tag, attrs)
        self.handle_endtag(tag)

    def handle_endtag(self, tag):
        if tag == "head":
            self._in_head_depth = 0
            return
        if self._in_head_depth > 0:
            self._in_head_depth -= 1
            return
        # Pop the matching frame.
        for i in range(len(self._stack) - 1, -1, -1):
            if self._stack[i]["tag"] == tag:
                del self._stack[i:]
                return

    def handle_data(self, data):
        if self._in_head_depth > 0 or not self._stack:
            return
        text = data
        # Bubble text up to every ancestor record so hashes reflect content.
        for frame in self._stack:
            rec = frame["record"]
            if rec is not None:
                rec["text"] += text


def _is_slide(tag: str, attrs: dict) -> bool:
    if tag in _SLIDE_TAGS:
        classes = (attrs.get("class") or "").split()
        if any(c in _SLIDE_CLASS_HINTS for c in classes):
            return True
        if (attrs.get("id") or "").startswith("slide"):
            return True
    return False


def _line_col_to_offset(source: str, line: int, col: int) -> int:
    offset = 0
    current = 1
    while current < line:
        nl = source.find("\n", offset)
        if nl == -1:
            return len(source)
        offset = nl + 1
        current += 1
    return offset + col


def _extract_tag_text(source: str, pos: int) -> str | None:
    if pos >= len(source) or source[pos] != "<":
        return None
    end = source.find(">", pos)
    if end == -1:
        return None
    return source[pos:end + 1]


def _assign_oids(
    records: list[dict],
    strategy: str,
    used: set[str],
) -> None:
    """Mutate records in place, adding an `oid` field."""
    slide_index = -1
    counter = 0
    for rec in records:
        if rec["is_slide"]:
            slide_index += 1
            counter = 0
        slide = max(slide_index, 0)

        if strategy == "sequential":
            base = f"s{slide}-o{counter}"
        elif strategy == "hash":
            text = rec["text"].strip()
            payload = f"{rec['tag']}|{rec['attrs'].get('class','')}|{rec['attrs'].get('id','')}|{text}"
            digest = hashlib.sha1(payload.encode("utf-8")).hexdigest()[:8]
            base = f"s{slide}-{digest}"
        elif strategy == "role":
            role = "slide" if rec["is_slide"] else _TAG_ROLE.get(rec["tag"], rec["tag"])
            base = f"s{slide}-{role}"
        else:
            raise ValueError(f"unknown strategy: {strategy}")

        rec["oid"] = _unique(base, used)
        counter += 1


def _unique(base: str, used: set[str]) -> str:
    if base not in used:
        used.add(base)
        return base
    i = 2
    while f"{base}-{i}" in used:
        i += 1
    oid = f"{base}-{i}"
    used.add(oid)
    return oid


def _inject_attribute(tag_text: str, name: str, value: str) -> str:
    """Insert `name="value"` after the tag name, preserving the rest verbatim."""
    m = re.match(r"<\s*([A-Za-z][A-Za-z0-9:-]*)", tag_text)
    if not m:
        return tag_text
    insert_at = m.end()
    return f'{tag_text[:insert_at]} {name}="{value}"{tag_text[insert_at:]}'


def adopt_html(html: str, strategy: str = "role") -> str:
    """Return `html` with `data-oid` injected on every meaningful element."""
    if strategy not in _STRATEGIES:
        raise ValueError(
            f"unknown strategy: {strategy} (expected one of {sorted(_STRATEGIES)})"
        )

    parser = _CollectParser(html)
    parser.feed(html)

    if not parser.records:
        return html

    used = set(parser.preserved_oids)
    _assign_oids(parser.records, strategy, used)

    out = html
    for rec in sorted(parser.records, key=lambda r: r["pos"], reverse=True):
        replacement = _inject_attribute(rec["tag_text"], "data-oid", rec["oid"])
        out = out[: rec["pos"]] + replacement + out[rec["pos"] + len(rec["tag_text"]):]
    return out
